RankenSchedule.UI/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using RankenSchedule.UI.Models.DataLayer;
using RankenSchedule.UI.Models.DomainModels;

namespace RankenSchedule.UI.Controllers
{
    public class ClassController : Controller
    {
        private Repository<Class> classes { get; set; }
        private Repository<Teacher> teachers { get; set; }
        private Repository<Day> days { get; set; }
        public ClassController(ClassScheduleContext ctx)
        {
            classes = new Repository<Class>(ctx);
            teachers = new Repository<Teacher>(ctx);
            days = new Repository<Day>(ctx);
        }

        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add()
        {
            this.LoadViewBag("Add");
            return View("AddEdit", new Class());
        }

        [HttpPost]
        public IActionResult Add(Class c)
        {
            bool isAdd = c.ClassId == 0;

            if (ModelState.IsValid)
            {
                if (isAdd)
                    classes.Insert(c);
                else
                    classes.Update(c);
                classes.Save();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                string opertaion = (isAdd) ? "Add" : "Edit";
                this.LoadViewBag(opertaion);
                return View("AddEdit", c);
            }
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            this.LoadViewBag("Edit");
            var c = this.GetClass(id);
            return View("AddEdit", c);
        }

        [HttpGet]
        public ViewResult Delete(int id)
        {
            var c = this.GetClass(id);
            return View(c);
        }

        [HttpPost]
        public RedirectToActionResult Delete(Class c)
        {
            classes.Delete(c);
            classes.Save();
            return RedirectToAction("Index", "Home");
        }

        //helper methods
        private Class GetClass(int id)
        {
            var classOptions = new QueryOption<Class>
            {
                Includes = "Teacher, Day",
                Where = c => c.ClassId == id
            };
            return classes.Get(classOptions) ?? new Class();
        }
        private void LoadViewBag(string Opertion)
        {
            ViewBag.Days = days.List(new QueryOption<Day>
            {
                OrderBy = d => d.DayId
            });
            ViewBag.Teachers = teachers.List(new QueryOption<Teacher>
            {
                OrderBy = teachers => teachers
            });
            ViewBag.Operation = Opertion;

        }
    }
}

RankenSchedule.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RankenSchedule.UI.Models.DataLayer;
using RankenSchedule.UI.Models.DomainModels;

namespace RankenSchedule.UI.Controllers
{
    public class HomeController : Controller
    {
        private Repository<Class> classes { get; set; }
        private Repository<Day> days { get; set; }
        public HomeController(ClassScheduleContext context)
        {
            classes = new Repository<Class>(context);
            days = new Repository<Day>(context);
        }

        public IActionResult Index(int id)
        {
            var dayOptions = new QueryOption<Day>
            {
                OrderBy = d => d.DayId
            };
            var classOptions = new QueryOption<Class>
            {
                Includes = "Teacher,Day"
            };

            if(id == 0)
            {
                classOptions.OrderBy =c => c.DayId;
                classOptions.ThenOrderBy =c => c.MilitaryTime;
            }
            else
            {
                classOptions.Where = c => c.DayId == id;
                classOptions.OrderBy = c => c.MilitaryTime;
            }

            //Executing the queries
            var dayList = days.List(dayOptions);
            var classList = classes.List(classOptions);

            //sending the data to the view
            ViewBag.Id = id;
            ViewBag.Days = dayList;


            return View(classList);
        }

    }
}

RankenSchedule.UI/Views/Home/Index.cshtml
@model IEnumerable<RankenSchedule.UI.Models.DomainModels.Class>
@{
    ViewData["Title"] = "Class Schedule";
}

<div class="text-center">
    <h1>Class Schedule</h1>
    @foreach (Day d in ViewBag.Days)
    {
        string btnCss = (ViewBag.id == d.DayId) ? "btn btn-dark" : "btn btn-outline-dark";
        <a asp-action="Index" asp-route-id="@d.DayId" class="@btnCss me-1 mb-2">@d.Name</a>
    }
</div>

<a asp-action="Add" asp-controller="Class">Add Class</a>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Number</th>
            <th>Teacher</th>
            <th>Day</th>
            <th>Time</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(Class c in Model)
        {
            <tr>
                <td>@c.Title</td>
                <td>@c.Number</td>
                <td>@c.Teacher.FullName</td>
                <td>@c.Day.Name</td>
                <td>@c.MilitaryTime</td>
                <td>
                    <a asp-action="Edit" asp-controller="Class" asp-route-id="@c.ClassId" asp-route-slug="@c.slug" class="btn btn-outline-dark">Edit</a>
                    <a asp-action="Delete" asp-controller="Class" asp-route-id="@c.ClassId" asp-route-slug="@c.slug" class="btn btn-outline-dark">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>